/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Apr 29 17:19:23 2019. */

#include "notificationsClearIndicatorDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t notifications_ClearIndicatorDirectivePayloadProto_fields[1] = {
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
